name: "Goose"
description: "Github Action for Goose"
author: shyaminayesh
branding:
  color: blue
  icon: box
runs:
  using: "docker"
  image: "docker://ghcr.io/enkodin/goose:latest"
inputs:
  command:
    description: "goose command"
    required: true
    default: "status"
  driver:
    description: "goose database driver"
    required: true
    default: "mysql"
  dbstring:
    description: "goose database connection string"
    required: true
  directory:
    description: "goose database migration directory"
    required: true
