name: "Goose"
description: "Github Action for Goose"
author: shyaminayesh
branding:
  color: blue
  icon: box
runs:
  using: "docker"
  image: "docker://ghcr.io/enkodin/goose:latest"
  args:
    - ${{ inputs.command }}
